log2timeline/dfdatetime

dfdatetime/cocoa_time.py, dfdatetime/delphi_date_time.py, dfdatetime/fake_time.py, dfdatetime/fat_date_time.py, dfdatetime/filetime.py, dfdatetime/hfs_time.py, dfdatetime/interface.py, dfdatetime/java_time.py, dfdatetime/ole_automation_date.py, dfdatetime/posix_time.py, dfdatetime/precisions.py, dfdatetime/rfc2579_date_time.py, dfdatetime/semantic_time.py, dfdatetime/systemtime.py, dfdatetime/time_elements.py, dfdatetime/uuid_time.py, dfdatetime/webkit_time.py, tests/cocoa_time.py, tests/delphi_date_time.py, tests/java_time.py, tests/ole_automation_date.py, tests/precisions.py, tests/rfc2579_date_time.py, tests/systemtime.py, tests/time_elements.py, tests/uuid_time.py, tests/webkit_time.py
[Code review: 337640043: Replace float with decimal for normalized timestamps.](https://codereview.appspot.com/337640043/)
=> 337640043: Replace float with decimal for normalized timestamps.

setup.py
Changes to setup.py to support Fedora Core 29
=> Changes to setup.py to support Fedora Core 29

dfdatetime/java_time.py, dfdatetime/posix_time.py, tests/cocoa_time.py, tests/fake_time.py, tests/fat_date_time.py, tests/filetime.py, tests/hfs_time.py, tests/posix_time.py, tests/time_elements.py
Moved JavaTime functionality into PosixTimeInMilliseconds
=> Moved JavaTime functionality into PosixTimeInMilliseconds

config/travis/install.sh
=> Moved pylint to separate PPA

setup.cfg
Changes to setup.cfg for building wheel
=> Changes to setup.cfg for building wheel

test_dependencies.ini
=> Added test_dependencies.ini

utils/check_dependencies.py, utils/dependencies.py
Updated check dependencies script
=> Updated check dependencies script

.pylintrc, dfdatetime/apfs_time.py, dfdatetime/interface.py, dfdatetime/precisions.py, dfdatetime/rfc2579_date_time.py, dfdatetime/semantic_time.py, tests/delphi_date_time.py, tests/interface.py, tests/rfc2579_date_time.py, tests/semantic_time.py, utils/dependencies.py
=> Changes for linter

.travis.yml, appveyor.yml, config/dpkg/changelog, config/travis/runtests.sh, dfdatetime/__init__.py
Changes to Travis CI test coverage
=> Changes to Travis CI test coverage

.travis.yml, config/travis/install.sh, config/travis/runtests.sh, dfdatetime.ini, setup.cfg, setup.py
Applied updates and added Fedora Core CI tests
Generated with: https://github.com/log2timeline/l2tdevtools/pull/582
=> Applied updates and added Fedora Core CI tests

.travis.yml, config/travis/install.sh, config/travis/runtests.sh
Applied updates and added Ubuntu 18.04 CI tests
=> Applied updates and added Ubuntu 18.04 CI tests

config/travis/install.sh, config/travis/runtests.sh
=> Updated dependencies

appveyor.yml, config/travis/install.sh, config/travis/runtests.sh, utils/dependencies.py
Changed AppVeyor test to use Python 3.7
=> Changed AppVeyor test to use Python 3.7

appveyor.yml
Changes to build Python wheel on AppVeyor
=> Changes to build Python wheel on AppVeyor

config/dpkg/rules, test_dependencies.ini
Removed Python 2 from dpkg files
=> Removed Python 2 from dpkg files

.travis.yml, config/dpkg/rules
Applied updates and added Python 3.8 CI tests
=> Applied updates and added Python 3.8 CI tests

.travis.yml, config/travis/install.sh, config/travis/run_pylint.sh, setup.py
Changed pylint CI test to Ubuntu 20.04
=> Changed pylint CI test to Ubuntu 20.04

dfdatetime/time_elements.py, tests/time_elements.py
Extended time elements with copy from datetime object #104
=> Extended time elements with copy from datetime object #104

config/dpkg/changelog, dfdatetime/__init__.py, dfdatetime/apfs_time.py, dfdatetime/cocoa_time.py, dfdatetime/delphi_date_time.py, dfdatetime/factory.py, dfdatetime/fat_date_time.py, dfdatetime/filetime.py, dfdatetime/hfs_time.py, dfdatetime/java_time.py, dfdatetime/ole_automation_date.py, dfdatetime/posix_time.py, dfdatetime/rfc2579_date_time.py, dfdatetime/semantic_time.py, dfdatetime/systemtime.py, dfdatetime/time_elements.py, dfdatetime/uuid_time.py, dfdatetime/webkit_time.py, tests/factory.py
Added date and time values factory class for serialization
=> Added date and time values factory class for serialization

config/dpkg/changelog, dfdatetime/__init__.py, dfdatetime/rfc2579_date_time.py, dfdatetime/time_elements.py, tests/time_elements.py
Added read-only properties to RFC2579DateTime and TimeElements
=> Added read-only properties to RFC2579DateTime and TimeElements

.travis.yml, config/dpkg/control, setup.py, tox.ini
Updated dependencies and added ppc64le Travis CI test targets
=> Updated dependencies and added ppc64le Travis CI test targets

.travis.yml, config/travis/install.sh
Added MacOS 10.15 with Python 3.8 CI test
=> Added MacOS 10.15 with Python 3.8 CI test

.github/workflows/test_docker.yml, .github/workflows/test_tox.yml, appveyor.yml
Changes to CI test configurations
=> Changes to CI test configurations

appveyor.yml, docs/conf.py, utils/dependencies.py
Changed Windows CI tests to use Python 3.9
=> Changed Windows CI tests to use Python 3.9

config/dpkg/changelog, dfdatetime/__init__.py, dfdatetime/ole_automation_date.py, docs/sources/Date-and-time-values.md, docs/sources/api/dfdatetime.rst, docs/sources/user/Installation-instructions.md, utils/update_release.sh
Updated version and documenation
=> Updated version and documenation

config/appveyor/install.ps1, docs/sources/user/Installation-instructions.md, setup.py
=> Changes for using main branch

dfdatetime/apfs_time.py, dfdatetime/cocoa_time.py, dfdatetime/delphi_date_time.py, dfdatetime/fake_time.py, dfdatetime/fat_date_time.py, dfdatetime/filetime.py, dfdatetime/hfs_time.py, dfdatetime/java_time.py, dfdatetime/ole_automation_date.py, dfdatetime/posix_time.py, dfdatetime/rfc2579_date_time.py, dfdatetime/systemtime.py, dfdatetime/time_elements.py, dfdatetime/uuid_time.py, dfdatetime/webkit_time.py, tests/apfs_time.py, tests/cocoa_time.py, tests/delphi_date_time.py, tests/fake_time.py, tests/fat_date_time.py, tests/filetime.py, tests/hfs_time.py, tests/java_time.py, tests/ole_automation_date.py, tests/posix_time.py, tests/rfc2579_date_time.py, tests/systemtime.py, tests/time_elements.py, tests/uuid_time.py, tests/webkit_time.py
Changes for time zone offset support #47
=> Changes for time zone offset support #47

config/dpkg/changelog, dfdatetime/__init__.py, dfdatetime/interface.py, tests/cocoa_time.py, tests/delphi_date_time.py, tests/fake_time.py, tests/fat_date_time.py, tests/filetime.py, tests/hfs_time.py, tests/java_time.py, tests/ole_automation_date.py, tests/posix_time.py, tests/rfc2579_date_time.py, tests/semantic_time.py, tests/systemtime.py, tests/time_elements.py, tests/uuid_time.py, tests/webkit_time.py
Added GetDateWithTimeOfDay method #186
=> Added GetDateWithTimeOfDay method #186

.github/workflows/test_docker.yml, docs/conf.py, docs/requirements.txt
=> Added Fedora 34 CI test

config/dpkg/changelog, dfdatetime/__init__.py, dfdatetime/cocoa_time.py, dfdatetime/delphi_date_time.py, dfdatetime/fat_date_time.py, dfdatetime/filetime.py, dfdatetime/hfs_time.py, dfdatetime/ole_automation_date.py, dfdatetime/posix_time.py, dfdatetime/uuid_time.py, dfdatetime/webkit_time.py
=> Added fat_date_time property
